IS_TENNIS = False
# if False is badminton

if IS_TENNIS: # tennis
    SINGLE_LINE_WIDTH = 8.23
    DOUBLE_LINE_WIDTH = 10.97
    HALF_COURT_LINE_HEIGHT = 11.88
    SERVICE_LINE_WIDTH = 6.4
    DOUBLE_ALLY_DIFFERENCE = 1.37
    NO_MANS_LAND_HEIGHT = 5.48
else: # badminton
    SINGLE_LINE_WIDTH = 5.06
    DOUBLE_LINE_WIDTH = 6.1
    HALF_COURT_LINE_HEIGHT = 6.7
    DOUBLE_ALLY_DIFFERENCE = 0.42
    DOUBLE_BOTTOM_DIFFERENCE = 0.72
    NO_MANS_LAND_HEIGHT = 4.72

PLAYER_1_HEIGHT_METERS = 1.88
PLAYER_2_HEIGHT_METERS = 1.91